import "server-only";

import { Types } from "mongoose";

import {
  AuditAction,
  AuditEntity,
} from "@/lib/constants/enums";
import { NotFoundError, ValidationError } from "@/lib/errors";
import {
  Document,
  DocumentKind,
  DocumentSequence,
  type DocumentDoc,
  type DocumentSnapshot,
} from "@/server/db/models";
import { connectMongo } from "@/server/db/mongoose";
import { orgIdFilter } from "@/server/db/org/org-context";

import { getBranding } from "./branding.service";
import { getOrderById } from "./order.service";
import { getOrganization } from "./organization.service";
import { recordAudit } from "./audit.service";
import type { RequestContext } from "@/server/api/request-context";
import type { OrderDTO } from "@/types";

/**
 * Document service — issue + read accounting documents (invoices,
 * receipts) for an order.
 *
 * Invariants:
 *   - Documents are append-only. `issueDocument` is the ONLY write
 *     path. The model enforces this via update-hooks too.
 *   - Numbering is monotonic per (orgId, kind), allocated atomically
 *     via DocumentSequence so concurrent issues don't collide.
 *   - Every read goes through this service and uses the stored
 *     snapshot — never re-derives from the live Order/Branding/Org.
 *     Once issued, the document is frozen evidence.
 *
 * MVP storage is HTML only. PDF is generated by the user's browser
 * via a print-stylesheet route, downloaded via "Save as PDF". When a
 * tenant needs true PDF blobs (e.g. for email attachment), swap the
 * renderer for @react-pdf or html-pdf-node — the service interface
 * stays the same.
 */

export interface DocumentDTO {
  id: string;
  orgId: string;
  orderId: string;
  kind: DocumentKind;
  number: string;
  issuedAt: string;
  issuedByUserId: string | null;
  snapshot: DocumentSnapshot;
}

function toDTO(doc: DocumentDoc & { _id: Types.ObjectId }): DocumentDTO {
  return {
    id: String(doc._id),
    orgId: String(doc.orgId),
    orderId: String(doc.orderId),
    kind: doc.kind,
    number: doc.number,
    issuedAt: doc.issuedAt.toISOString(),
    issuedByUserId: doc.issuedByUserId ? String(doc.issuedByUserId) : null,
    snapshot: doc.snapshot as unknown as DocumentSnapshot,
  };
}

/* ──────────────────────── Number allocation ─────────────────────────── */

/**
 * Atomic next-number allocator. Single $inc on the per-(orgId, kind)
 * sequence doc. Returns a tenant-friendly formatted number like
 * "INV-2026-0001".
 *
 * Why the format includes the year: keeps numbers operator-readable
 * across multiple fiscal years without colliding across tenants
 * (the orgId scope already guarantees no inter-tenant collision).
 */
async function allocateNextNumber(
  orgId: string,
  kind: DocumentKind,
): Promise<string> {
  const updated = await DocumentSequence.findOneAndUpdate(
    { orgId: orgIdFilter(orgId), kind },
    { $inc: { lastIssuedSeq: 1 }, $setOnInsert: { orgId: orgIdFilter(orgId), kind } },
    { upsert: true, returnDocument: "after", setDefaultsOnInsert: true },
  ).lean<{ lastIssuedSeq: number }>();
  if (!updated) {
    throw new Error("Failed to allocate document number");
  }
  return formatDocumentNumber(kind, updated.lastIssuedSeq);
}

function formatDocumentNumber(kind: DocumentKind, seq: number): string {
  const prefix = kind === DocumentKind.INVOICE ? "INV" : "RCP";
  const year = new Date().getUTCFullYear();
  return `${prefix}-${year}-${String(seq).padStart(4, "0")}`;
}

/* ──────────────────────── Snapshot builder ──────────────────────────── */

/**
 * Build the frozen snapshot the renderer reads. Pulls every field
 * from the LIVE order + branding + org so the document captures
 * everything as of the moment-of-issue.
 */
async function buildSnapshot(
  order: OrderDTO,
  orgId: string,
): Promise<DocumentSnapshot> {
  const [branding, organization] = await Promise.all([
    getBranding(orgId),
    getOrganization(orgId),
  ]);
  const subtotal = order.lineItems.reduce(
    (sum, li) => sum + li.total,
    0,
  );
  return {
    brand: {
      name: branding.brandName,
      supportEmail: branding.supportEmail,
      supportPhone: branding.supportPhone,
      primaryColor: branding.primaryColor,
      logo: branding.logo || null,
      legalName: organization.legalName ?? null,
    },
    customer: {
      name: order.customer.name,
      email: order.customer.email,
      phone: order.customer.phone ?? null,
    },
    lineItems: order.lineItems.map((li) => ({
      name: li.name,
      description: li.description ?? null,
      quantity: li.quantity,
      unitPrice: li.unitPrice,
      total: li.total,
    })),
    pricing: {
      subtotal,
      // Tax engine not built yet (Phase 11 in the roadmap). When it
      // lands, this becomes the sum of per-line tax. Until then the
      // grand total equals the subtotal.
      taxTotal: 0,
      grandTotal: order.pricing.amount,
      currency: order.pricing.currency,
      amountReceived: order.payment.amountReceived ?? null,
      paidAt: order.payment.paidAt ?? null,
    },
    order: {
      orderNumber: order.orderNumber,
      createdAt: order.createdAt,
    },
  };
}

/* ──────────────────────────── Write paths ───────────────────────────── */

export interface IssueDocumentInput {
  orderId: string;
  kind: DocumentKind;
}

export interface IssueDocumentContext {
  actor: { id: string; name: string; email: string; role: string };
  orgId: string;
  request?: RequestContext | null;
}

/**
 * Issue a new document for an order. Allocates the next number,
 * snapshots the order + branding + org into the doc, renders + stores
 * the HTML.
 *
 * Idempotency: NOT enforced here. Re-issuing a receipt for the same
 * order is allowed (some tenants reissue with corrections). The
 * RECEIPT-on-payment auto-trigger (when built) should dedupe its own
 * way via the order's `confirmationEmailSentAt`-style flag.
 */
export async function issueDocument(
  input: IssueDocumentInput,
  ctx: IssueDocumentContext,
): Promise<DocumentDTO> {
  await connectMongo();
  if (!Types.ObjectId.isValid(input.orderId)) {
    throw new ValidationError("Invalid orderId");
  }
  if (input.kind !== DocumentKind.INVOICE && input.kind !== DocumentKind.RECEIPT) {
    throw new ValidationError(`Unsupported document kind: ${input.kind}`);
  }

  // Fetch the order pinned to the actor's org — refuses cross-tenant
  // issues even with a guessed orderId.
  const orderResult = await getOrderById(input.orderId, {
    actor: ctx.actor as never,
    orgId: ctx.orgId,
    request: null,
  });
  if (!orderResult) throw new NotFoundError("Order not found");

  // RECEIPT semantics — must be against a paid order. INVOICE can be
  // issued at any point in the order lifecycle (some businesses issue
  // proforma invoices before payment).
  if (
    input.kind === DocumentKind.RECEIPT &&
    !orderResult.payment.paidAt
  ) {
    throw new ValidationError(
      "Cannot issue a receipt for an order that hasn't been paid yet",
    );
  }

  const snapshot = await buildSnapshot(orderResult, ctx.orgId);
  const number = await allocateNextNumber(ctx.orgId, input.kind);
  const html = renderDocumentHTML({ snapshot, kind: input.kind, number });

  let created: DocumentDoc & { _id: Types.ObjectId };
  try {
    created = (await Document.create({
      orgId: new Types.ObjectId(ctx.orgId),
      orderId: new Types.ObjectId(input.orderId),
      kind: input.kind,
      number,
      issuedAt: new Date(),
      issuedByUserId: ctx.actor?.id
        ? new Types.ObjectId(ctx.actor.id)
        : null,
      snapshot: snapshot as unknown as Record<string, unknown>,
      htmlSnapshot: html,
    })) as unknown as DocumentDoc & { _id: Types.ObjectId };
  } catch (err) {
    // Number-collision races are exceedingly rare given the atomic
    // $inc, but a duplicate-key error here means another concurrent
    // issue beat us — surface a clean retryable signal.
    if ((err as { code?: number }).code === 11000) {
      throw new ValidationError(
        "Document number collision — retry the issue",
      );
    }
    throw err;
  }

  await recordAudit({
    action: AuditAction.SETTINGS_UPDATED,
    entityType: AuditEntity.SETTINGS,
    entityId: String(created._id),
    orgId: ctx.orgId,
    actor: {
      userId: ctx.actor.id,
      name: ctx.actor.name,
      email: ctx.actor.email,
      role: ctx.actor.role as never,
    },
    request: ctx.request ?? null,
    metadata: {
      documentKind: input.kind,
      documentNumber: number,
      orderId: input.orderId,
      orderNumber: orderResult.orderNumber,
    },
  });

  return toDTO(created);
}

/* ──────────────────────────── Read paths ────────────────────────────── */

export async function getDocumentById(
  id: string,
  ctx: { orgId: string },
): Promise<DocumentDTO> {
  await connectMongo();
  if (!Types.ObjectId.isValid(id)) {
    throw new NotFoundError("Document not found");
  }
  const doc = await Document.findOne({
    _id: id,
    orgId: orgIdFilter(ctx.orgId),
  }).lean<DocumentDoc & { _id: Types.ObjectId }>();
  if (!doc) throw new NotFoundError("Document not found");
  return toDTO(doc);
}

/** Same as getDocumentById but also returns the stored HTML — used
 *  by the render route. */
export async function getDocumentForRender(
  id: string,
  ctx: { orgId: string },
): Promise<{ dto: DocumentDTO; html: string }> {
  await connectMongo();
  if (!Types.ObjectId.isValid(id)) {
    throw new NotFoundError("Document not found");
  }
  const doc = await Document.findOne({
    _id: id,
    orgId: orgIdFilter(ctx.orgId),
  }).lean<DocumentDoc & { _id: Types.ObjectId }>();
  if (!doc) throw new NotFoundError("Document not found");
  return { dto: toDTO(doc), html: doc.htmlSnapshot };
}

export async function listDocumentsForOrder(
  orderId: string,
  ctx: { orgId: string },
): Promise<DocumentDTO[]> {
  await connectMongo();
  if (!Types.ObjectId.isValid(orderId)) return [];
  const docs = await Document.find({
    orderId: new Types.ObjectId(orderId),
    orgId: orgIdFilter(ctx.orgId),
  })
    .sort({ issuedAt: -1 })
    .lean<(DocumentDoc & { _id: Types.ObjectId })[]>();
  return docs.map(toDTO);
}

/* ──────────────────────────── HTML renderer ─────────────────────────── */

/**
 * Render the document HTML. Uses inline styles + a print stylesheet
 * so the browser's "Save as PDF" produces a clean single-page PDF
 * with the tenant's brand color. No external CSS / fonts — keeps the
 * print output deterministic across browsers.
 *
 * Exported because the issue path renders + persists. Re-renders for
 * download always read the frozen `htmlSnapshot` from Mongo (never
 * re-call this); the function is here as the build-time renderer.
 */
export function renderDocumentHTML(args: {
  snapshot: DocumentSnapshot;
  kind: DocumentKind;
  number: string;
}): string {
  const { snapshot, kind, number } = args;
  const title = kind === DocumentKind.INVOICE ? "Invoice" : "Receipt";
  const accent = snapshot.brand.primaryColor || "#0F172A";
  const fmt = (n: number) =>
    new Intl.NumberFormat("en-US", {
      style: "currency",
      currency: snapshot.pricing.currency,
    }).format(n);
  const escape = (s: string) =>
    s
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;")
      .replace(/'/g, "&#39;");

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>${escape(title)} ${escape(number)} · ${escape(snapshot.brand.name)}</title>
<meta name="robots" content="noindex,nofollow" />
<style>
  *, *::before, *::after { box-sizing: border-box; }
  html, body { margin: 0; padding: 0; background: #FFFFFF; color: #0F172A; font-family: ui-sans-serif, system-ui, -apple-system, "Segoe UI", Inter, Helvetica, Arial, sans-serif; font-size: 13px; line-height: 1.5; }
  .page { max-width: 760px; margin: 0 auto; padding: 56px 48px; }
  .header { display: flex; align-items: flex-start; justify-content: space-between; gap: 24px; padding-bottom: 28px; border-bottom: 1px solid #E2E8F0; }
  .brand { display: flex; align-items: center; gap: 12px; }
  .brand-logo { width: 36px; height: 36px; border-radius: 6px; object-fit: contain; }
  .brand-name { font-size: 16px; font-weight: 600; letter-spacing: -0.01em; }
  .doc-meta { text-align: right; }
  .doc-title { font-size: 22px; font-weight: 700; letter-spacing: -0.02em; color: ${escape(accent)}; }
  .doc-sub { font-size: 11px; color: #64748B; text-transform: uppercase; letter-spacing: 0.12em; margin-top: 4px; }
  .doc-number { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 13px; margin-top: 12px; }
  .grid-2 { display: grid; grid-template-columns: 1fr 1fr; gap: 32px; margin: 32px 0 28px; }
  .section-label { font-size: 10.5px; color: #64748B; text-transform: uppercase; letter-spacing: 0.14em; font-weight: 600; margin-bottom: 6px; }
  table.items { width: 100%; border-collapse: collapse; margin-top: 12px; }
  table.items thead th { text-align: left; font-size: 10.5px; color: #64748B; text-transform: uppercase; letter-spacing: 0.14em; font-weight: 600; padding: 10px 0; border-bottom: 1px solid #E2E8F0; }
  table.items tbody td { padding: 12px 0; border-bottom: 1px solid #F1F5F9; vertical-align: top; }
  table.items tbody td.num { text-align: right; font-variant-numeric: tabular-nums; }
  .item-name { font-weight: 600; }
  .item-desc { font-size: 11.5px; color: #64748B; margin-top: 2px; }
  .totals { margin-top: 20px; display: flex; justify-content: flex-end; }
  .totals-table { width: 280px; }
  .totals-row { display: flex; justify-content: space-between; padding: 6px 0; font-size: 12.5px; }
  .totals-row.grand { font-weight: 700; font-size: 14px; padding-top: 10px; border-top: 1px solid #E2E8F0; margin-top: 6px; }
  .footer { margin-top: 48px; padding-top: 20px; border-top: 1px solid #E2E8F0; font-size: 11.5px; color: #64748B; display: flex; justify-content: space-between; gap: 24px; flex-wrap: wrap; }
  .badge-paid { display: inline-block; padding: 4px 8px; background: #DCFCE7; color: #166534; font-size: 10.5px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.1em; border-radius: 4px; margin-top: 8px; }
  .print-btn { position: fixed; top: 16px; right: 16px; padding: 8px 14px; background: ${escape(accent)}; color: white; border: 0; border-radius: 6px; font-size: 12px; font-weight: 600; cursor: pointer; font-family: inherit; }
  @media print { .print-btn { display: none; } body { font-size: 12px; } .page { padding: 32px 36px; } }
</style>
</head>
<body>
  <button class="print-btn" onclick="window.print()">Save as PDF</button>
  <div class="page">
    <div class="header">
      <div class="brand">
        ${snapshot.brand.logo ? `<img class="brand-logo" src="${escape(snapshot.brand.logo)}" alt="${escape(snapshot.brand.name)}" />` : ""}
        <div>
          <div class="brand-name">${escape(snapshot.brand.name)}</div>
          ${snapshot.brand.legalName ? `<div style="font-size:11px;color:#64748B;">${escape(snapshot.brand.legalName)}</div>` : ""}
        </div>
      </div>
      <div class="doc-meta">
        <div class="doc-title">${escape(title)}</div>
        <div class="doc-sub">${escape(snapshot.brand.name)}</div>
        <div class="doc-number">${escape(number)}</div>
        ${kind === DocumentKind.RECEIPT ? `<div class="badge-paid">Paid</div>` : ""}
      </div>
    </div>

    <div class="grid-2">
      <div>
        <div class="section-label">Billed to</div>
        <div style="font-weight:600;">${escape(snapshot.customer.name)}</div>
        <div style="color:#64748B;">${escape(snapshot.customer.email)}</div>
        ${snapshot.customer.phone ? `<div style="color:#64748B;">${escape(snapshot.customer.phone)}</div>` : ""}
      </div>
      <div style="text-align:right;">
        <div class="section-label">Order</div>
        <div style="font-family:ui-monospace,SFMono-Regular,Menlo,monospace;">${escape(snapshot.order.orderNumber)}</div>
        <div style="color:#64748B; margin-top:4px;">${escape(formatDate(snapshot.order.createdAt))}</div>
        ${snapshot.pricing.paidAt ? `<div style="color:#64748B; margin-top:4px;">Paid ${escape(formatDate(snapshot.pricing.paidAt))}</div>` : ""}
      </div>
    </div>

    <table class="items">
      <thead>
        <tr>
          <th>Item</th>
          <th style="text-align:right; width: 80px;">Qty</th>
          <th style="text-align:right; width: 120px;">Unit</th>
          <th style="text-align:right; width: 120px;">Total</th>
        </tr>
      </thead>
      <tbody>
        ${snapshot.lineItems
          .map(
            (li) => `<tr>
          <td>
            <div class="item-name">${escape(li.name)}</div>
            ${li.description ? `<div class="item-desc">${escape(li.description)}</div>` : ""}
          </td>
          <td class="num">${li.quantity}</td>
          <td class="num">${fmt(li.unitPrice)}</td>
          <td class="num">${fmt(li.total)}</td>
        </tr>`,
          )
          .join("")}
      </tbody>
    </table>

    <div class="totals">
      <div class="totals-table">
        <div class="totals-row">
          <span>Subtotal</span>
          <span>${fmt(snapshot.pricing.subtotal)}</span>
        </div>
        ${snapshot.pricing.taxTotal > 0 ? `<div class="totals-row"><span>Tax</span><span>${fmt(snapshot.pricing.taxTotal)}</span></div>` : ""}
        <div class="totals-row grand">
          <span>${kind === DocumentKind.RECEIPT ? "Amount paid" : "Total due"}</span>
          <span>${fmt(snapshot.pricing.grandTotal)}</span>
        </div>
      </div>
    </div>

    <div class="footer">
      <div>
        Need help? Contact ${escape(snapshot.brand.supportEmail)}${snapshot.brand.supportPhone ? ` · ${escape(snapshot.brand.supportPhone)}` : ""}.
      </div>
      <div>${escape(snapshot.brand.name)} · ${escape(number)}</div>
    </div>
  </div>
</body>
</html>`;
}

function formatDate(iso: string): string {
  try {
    const d = new Date(iso);
    return d.toLocaleDateString("en-US", {
      year: "numeric",
      month: "short",
      day: "numeric",
    });
  } catch {
    return iso;
  }
}
