import { formatHashShort, formatUtcTimestamp } from "@/lib/format";

/**
 * Footer integrity statement on the case file. Two short paragraphs +
 * the chain head hash. Reads like the disclosure block at the bottom
 * of a regulated document — calm, formal, not decorative.
 */

interface IntegrityStatementProps {
  generatedAt: string;
  eventCount: number;
  headHash: string | null;
  valid: boolean;
}

export function IntegrityStatement({
  generatedAt,
  eventCount,
  headHash,
  valid,
}: IntegrityStatementProps) {
  return (
    <footer className="border-t border-border/70 px-8 py-7 text-[12px] leading-relaxed text-muted-foreground">
      <div className="grid gap-6 sm:grid-cols-[1fr_auto] sm:items-end">
        <div className="max-w-[64ch] space-y-2">
          <p>
            <span className="font-medium text-foreground">
              Integrity statement.
            </span>{" "}
            Each of the {eventCount} {eventCount === 1 ? "event" : "events"}{" "}
            in this case file is cryptographically chained against the
            previous one. Any tampering with a payload or timestamp
            cascades into every downstream hash and surfaces here as a{" "}
            <span
              className={
                valid ? "text-success" : "text-destructive font-medium"
              }
            >
              {valid ? "verified chain" : "broken chain"}
            </span>
            .
          </p>
          <p>
            This document was generated by tracetxn on{" "}
            {formatUtcTimestamp(generatedAt)}.
          </p>
        </div>

        {headHash ? (
          <div className="font-mono text-[11px] tabular-nums">
            <p className="text-muted-foreground">Chain head</p>
            <p className="mt-1 text-foreground">{formatHashShort(headHash, 16)}</p>
          </div>
        ) : null}
      </div>
    </footer>
  );
}
